Ensembl/ensembl-production-services

bin/gunicorn.sh, bin/nginx.sh
Sorry for the name of the source Branch :-) But this patch should solve the start-stop-daemon issue
=> Changed start script

ensembl_production/utils.py, ensembl_production_db/admin.py
Changed wed_data data check in back office
=> Fixed perl string validation

ensembl_production_db/api/urls.py, production_services/settings.py, production_services/urls.py, requirements.txt
Changing swagger ui to enable nested object documentation
=> Changed swagger ui

ensembl_production_db/api/serializers.py, ensembl_production_db/fixtures/ensembl_production_api.json, ensembl_production_db/tests.py
- WebData not updated in mass upon update for a analysis description
=> Correction:

ensembl_production_db/admin.py
Added Master Attrib ID in list. (Request from team)
=> Added MasterAttrib as filter / listed key in list display.

production_services/settings.py
Small typo in settings (duplicated entry)
=> Corrected typo in settings.py

production_services/settings_tests.py
Sorry, another "typo" correction :-)
=> Simplify test settings (not override everything)

ensembl_production/static/css/production_admin.css, ensembl_production_db/admin.py
And Update drop down css for available WebData lists
=> Fix new AnalysisDescription admin page error

ensembl_production/static/css/production_admin.css, ensembl_production_db/admin.py, ensembl_production_db/models.py
Tweak list display to show icons in admin lists
=> Field is_current enable in ExternalDB Admin page

production_services/settings.py
Redundant after we changed nginx configuration.
=> Disable USE_X_FORWARDED_HOST

ensembl_production/admin.py
Fixed error 500 when trying to access "admin/ensembl_production/productionflaskapp/add/ "
=> Fixed 500 when trying to add a new app.

ensembl_production/static/css/production_admin.css
Related to this bug: https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-5355
=> Adding css fix for analysis_description displayable column

ensembl_production_db/models.py
Re-enabled filtering web data per their db id.
=> Filter web data on their id.

ensembl_website/admin.py
Added drop down to select category of FAQ field.
=> Added drop down to select FAQ entry type.

ensembl_dbcopy/forms.py
Fix cases when the copy was blocked even though the target db name was different
=> Hotfix: Fix dbcopy source as target restricion bug

ensembl_intentions/admin.py, ensembl_intentions/management/commands/intention_export.py, ensembl_intentions/models.py, ensembl_intentions/templates/rapid.html, ensembl_intentions/templates/rapid_export.html
Added dedicated command to dump to file the expected content. Script to be put in ensprod cron tab for regulat dumps of RR bugs for WEB display.
=> Added RR bugs tickets export

ensembl_intentions/models.py
Added more filter in RR retrieval query
=> ENSRR-142 - updated query not to fetch Resolved / Done / Closed

Dockerfile, Dockerfile.nginx, README.md, bin/.env.sample, bin/gunicorn.sh, bin/nginx.sh, bin/nginx/Dockerfile, bin/nginx/nginx.conf, docker-compose.yml, requirements.txt
Docker files and config files to lauch  production service in a container
=> Docker files

requirements.in, requirements.txt, src/production_services/settings.py
- default dbs to actual target schema names
=> - updated metadata-admin to latest tag

CHANGELOG.md
- Updated apps to latest version
- ensembl-metadata-admin@git+https://github.com/Ensembl/ensembl-metadata-admin.git@0.0.4
- ensembl-prodinf-masterdb@git+https://github.com/Ensembl/ensembl-prodinf-masterdb.git@1.2.3
- ensembl-prodinf-jira@git+https://github.com/Ensembl/ensembl-prodinf-jira.git@2.0.3
- Added api endpoint to access new production metadata 
- api/genome_metadata/
- Fix for analysis description API, default JSON EXTRACT fails to filter with json object
=> change log for version 4.4.3
